[package]
name = "twine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
std = []

[dev-dependencies]
bumpalo = { version = "3.15.3", features = ["collections"] }
